"use client";
import { Check, ChevronRight, CircleDot, Flag, Plus, Sparkles, Swords, Trash2 } from "lucide-react";
import { useState } from "react";
import { practices, tracks, type TrackId } from "@/mocks/data";
import { useMockStore } from "@/mocks/store";
import { WorkoutFlow } from "@/features/workout/WorkoutFlow";
export function Trail(){const store=useMockStore();const [active,setActive]=useState<TrackId>("push");const [training,setTraining]=useState(false);const track=tracks.find(t=>t.id===active)!;const items=practices.filter(p=>p.track===active);return <><section className="page journey-page">
 <div className="journey-hero"><div><p className="eyebrow"><Sparkles/> SUA JORNADA</p><h1>Hoje você faz o que antes parecia distante.</h1><p>Cinco caminhos. O seu ritmo.</p></div><div className="journey-xp"><span>EXPERIÊNCIA</span><strong>{store.xp} XP</strong><small>XP celebra constância, não mede capacidade.</small></div></div>
 <div className="track-rail" aria-label="Cinco trilhas">{tracks.map(t=><button key={t.id} className={active===t.id?"active":""} style={{"--track":t.color} as React.CSSProperties} onClick={()=>setActive(t.id)}><i>{t.icon}</i><span>{t.name}</span><small>{t.capacity}</small></button>)}</div>
 <div className="journey-head"><div><span style={{color:track.color}}>TRILHA · {track.name.toUpperCase()}</span><h2>{track.reference}</h2><p>Seu caminho contínuo, sem níveis ou bloqueios.</p></div><div className="capacity-pill"><CircleDot/><span>Agora<strong>{track.capacity}</strong></span></div></div>
 <div className="path" style={{"--track":track.color} as React.CSSProperties}>{items.map((p,index)=><article className={`path-node ${p.status}`} key={p.id}><div className="node-line"/><span className="node-icon">{p.status==="dominado"?<Check/>:p.status==="atual"?<Sparkles/>:<ChevronRight/>}</span><div className="node-card card"><span className="node-status">{p.status==="dominado"?"DOMINADO":p.status==="atual"?"PRÁTICA DISPONÍVEL":"PRÓXIMO PASSO"}</span><h3>{p.name}</h3><p>EMOM 5 min · {p.dose} {p.unit==="reps"?"repetições":"segundos"}/min</p>{p.status!=="dominado"&&<button onClick={()=>store.add(p)} disabled={store.session.length>=5}><Plus/> ADICIONAR À SESSÃO</button>}</div>{index===1&&<aside className="checkpoint"><Flag/><span><strong>Checkpoint disponível</strong>{track.checkpoint}<small>Recalibra, nunca bloqueia.</small></span></aside>}</article>)}</div>
 <article className="cross-challenge"><Swords/><div><span>DESAFIO OPCIONAL · +80 XP</span><h3>{active==="pull"?"Puxar + Core":active==="legs"||active==="cardio"?"Pernas + Cardio":"Empurrar + Core"}</h3><p>Duas trilhas se encontram em um marco especial. Não bloqueia seu caminho.</p></div><button>VER DESAFIO</button></article>
 </section>{store.session.length>0&&<div className="session-dock"><div><span>SESSÃO DE HOJE</span><strong>{store.session.length} {store.session.length===1?"prática":"práticas"} · ≈ {store.session.length*5} min</strong></div><div className="session-chips">{store.session.map((p,i)=><button key={`${p.id}-${i}`} onClick={()=>store.remove(i)} title="Remover">{p.name}<Trash2/></button>)}</div><button className="primary-button" onClick={()=>setTraining(true)}>INICIAR SESSÃO <ChevronRight/></button></div>}{training&&<WorkoutFlow onClose={()=>setTraining(false)}/>}</>}
