"use client";
import { CalendarDays, Check, ChevronRight, LockKeyhole, Play, Trophy, X } from "lucide-react";
import { useState, type CSSProperties } from "react";
import { TrackIcon } from "@/components/icons/TrackIcon";
import { type Track, type TrackId } from "@/mocks/data";
import { sessionDuration, useMockStore } from "@/mocks/store";
import { WorkoutFlow } from "@/features/workout/WorkoutFlow";

function TrackDetail({track,onClose}:{track:Track;onClose:()=>void}){const max=Math.max(...track.history.map(item=>item.volume));return <div className="detail-sheet" role="dialog" aria-modal="true" aria-label={`Histórico de ${track.name}`} style={{"--track":track.color} as CSSProperties}><header><div className="track-heading"><span className="track-icon"><TrackIcon track={track.id}/></span><div><small>TRILHA</small><h2>{track.name}</h2></div></div><button onClick={onClose} aria-label="Fechar histórico"><X/></button></header><div className="detail-body"><p className="eyebrow">SUA EVOLUÇÃO</p><h3>{track.exercise}</h3><div className="metric-cards"><article><span>Último resultado</span><strong>{track.history.at(-1)?.volume??"—"}</strong><small>repetições totais</small></article><article><span>Recorde pessoal</span><strong>{track.personalBest}</strong><small>repetições totais</small></article><article><span>Esta semana</span><strong>{track.weekly}</strong><small>repetições totais</small></article><article><span>Desde o início</span><strong>{track.accumulated.toLocaleString("pt-BR")}</strong><small>repetições acumuladas</small></article></div><div className="history-chart" aria-label="Evolução temporal">{track.history.map(item=><div key={item.id}><span>{item.volume}</span><i style={{height:`${Math.max(18,item.volume/max*100)}%`}}/><small>{new Date(`${item.date}T12:00:00`).toLocaleDateString("pt-BR",{day:"2-digit",month:"short"})}</small></div>)}</div><h3>Histórico</h3><div className="history-list">{track.history.length?<>{track.history.slice().reverse().map((item,index)=><article key={item.id}><CalendarDays/><div><strong>{item.exercise}</strong><span>{new Date(`${item.date}T12:00:00`).toLocaleDateString("pt-BR")}</span></div><b>{item.sets} × {item.repsPerSet} = {item.volume}<small> repetições</small>{index===0&&item.volume===track.personalBest?<em><Trophy/> RECORDE</em>:null}</b></article>)}</>:<p className="empty-state">Sua primeira prática aparecerá aqui.</p>}</div></div></div>}

export function JourneyTrack({track,selected,unavailable,onToggle,onHistory}:{track:Track;selected:boolean;unavailable:boolean;onToggle:()=>void;onHistory:()=>void}){return <article className="journey-card" style={{"--track":track.color} as CSSProperties} data-track={track.id}><header><div className="track-heading"><span className="track-icon"><TrackIcon track={track.id}/></span><div><small>TRILHA DE MOVIMENTO</small><h2>{track.name}</h2></div></div><button className="text-button" onClick={onHistory}>Ver evolução <ChevronRight/></button></header><p>{track.exercise} · progressão personalizada</p><div className="visual-path" aria-label={`Progresso de ${track.name}`}>{track.history.slice(-4).map((item,index)=><div className="checkpoint-wrap" key={item.id}><span className={`checkpoint ${item.volume===track.personalBest?"record":"complete"}`} aria-label={item.volume===track.personalBest?`Recorde de ${track.name}: ${item.volume} repetições`:`Sessão concluída: ${item.volume} repetições`}>{item.volume===track.personalBest?<Trophy/>:<Check/>}</span>{index<3&&<i/>}</div>)}<div className="checkpoint-wrap next"><span className={`checkpoint recommendation ${selected?"selected":""} ${unavailable?"unavailable":""}`}><Play/></span></div></div><div className="next-workout"><div><span>PRÓXIMO TREINO</span><strong>{track.recommendation} repetições × 5 séries</strong><small>{track.recommendation} × 5 = {track.recommendation*5} repetições totais</small></div><button type="button" disabled={unavailable} aria-pressed={selected} aria-label={`${selected?"Remover":"Selecionar"} sugestão de ${track.name}: ${track.recommendation} repetições por série`} onClick={onToggle}>{unavailable?<LockKeyhole/>:selected?<Check/>:<Play/>}{unavailable?"Limite atingido":selected?"Selecionado":"Adicionar"}</button></div></article>}

export function Trail(){const store=useMockStore();const [active,setActive]=useState<TrackId>("push");const [detail,setDetail]=useState<Track|null>(null);const [training,setTraining]=useState(false);const track=store.journeys.find(item=>item.id===active)!;function toggle(item:Track){const index=store.session.findIndex(p=>p.track===item.id);if(index>=0)store.remove(index);else store.addTrack(item.id)}return <><section className="journey-page"><div className="journey-title"><span>SEU PLANO DE CALISTENIA</span><h1>Construa força.<br/>Um movimento por vez.</h1><p>Escolha até duas trilhas para o treino de hoje.</p></div><div className="track-tabs" role="tablist" aria-label="Escolher trilha">{store.journeys.map(item=><button role="tab" aria-selected={active===item.id} key={item.id} className={active===item.id?"active":""} style={{"--track":item.color} as CSSProperties} onClick={()=>setActive(item.id)}><TrackIcon track={item.id}/><span>{item.name}</span></button>)}</div><JourneyTrack track={track} selected={store.session.some(item=>item.track===track.id)} unavailable={store.session.length===2&&!store.session.some(item=>item.track===track.id)} onToggle={()=>toggle(track)} onHistory={()=>setDetail(track)}/></section>{store.session.length>0&&<div className="start-training-dock"><div><span>TREINO DE HOJE · {store.session.length} {store.session.length===1?"TRILHA":"TRILHAS"}</span><strong>{sessionDuration(store.session)} min</strong></div><button className="primary-button" onClick={()=>setTraining(true)}>COMEÇAR <Play/></button></div>}{detail&&<TrackDetail track={detail} onClose={()=>setDetail(null)}/>} {training&&<WorkoutFlow onClose={()=>setTraining(false)}/>}</>}
