"use client";
import { useState } from "react";
import { tracks, type TrackId } from "@/mocks/data";
import { useMockStore } from "@/mocks/store";
import { repetitionsReference } from "@/features/workout/recommendationEngine";
export function Evolution() {
  const store = useMockStore(), [active, setActive] = useState<TrackId>("push"), track = tracks.find((item) => item.id === active)!;
  const all = store.sessions.filter((session) => session.prescriptions.some((item) => item.track === active));
  const done = all.filter((session) => session.status === "completed"), doses = done.flatMap((session) => session.prescriptions.filter((item) => item.track === active));
  const current = repetitionsReference(active, track.initialShortRecommendation, store.sessions), first = doses[0]?.repsPerSet, last = doses.at(-1)?.repsPerSet;
  const volume = doses.reduce((sum, item) => sum + item.totalVolume, 0), recent = doses.slice(-4).reduce((sum, item) => sum + item.totalVolume, 0), seconds = done.reduce((sum, session) => sum + session.elapsedSeconds / Math.max(1, session.prescriptions.length), 0);
  return <section className="page evolution-page"><div className="page-title"><p className="eyebrow">EVOLUÇÃO PESSOAL</p><h1>Sua história em {track.name}.</h1><p>{first && last ? `Você saiu de ${first} para ${last} por série.` : "Sua primeira sessão criará a referência."}</p></div><div className="track-tabs" aria-label="Escolher trilha">{tracks.map((item) => <button key={item.id} aria-pressed={active === item.id} onClick={() => setActive(item.id)}>{item.name}</button>)}</div><div className="metric-grid"><article><span>Último realizado</span><strong>{current}</strong><small>por série</small></article><article><span>Recorde por série</span><strong>{doses.length ? Math.max(...doses.map((item) => item.repsPerSet)) : "—"}</strong></article><article><span>Volume total executado</span><strong>{volume}</strong></article><article><span>Volume recente executado</span><strong>{recent}</strong></article><article><span>Tempo total</span><strong>{Math.floor(seconds / 60)} min</strong></article><article><span>Sessões concluídas</span><strong>{done.length}</strong></article><article><span>Interrompidas</span><strong>{all.length - done.length}</strong></article></div><article className="history-card"><h2>Histórico realizado</h2>{done.length ? <ol>{done.map((session) => { const item = session.prescriptions.find((entry) => entry.track === active)!; return <li key={session.id}><time>{new Date(`${session.date}T12:00:00`).toLocaleDateString("pt-BR")}</time><strong>{item.repsPerSet} por série</strong><span>{item.sets} séries · {item.totalVolume} no total</span></li>; })}</ol> : <p className="empty-state">Nenhuma sessão concluída nesta trilha.</p>}</article></section>;
}
