"use client";
import { Award, Clock3, Repeat2, Sparkles, TrendingUp } from "lucide-react";
import { evolution, tracks, type TrackId } from "@/mocks/data";
import { useMockStore } from "@/mocks/store";
import { useState } from "react";
export function Evolution(){const s=useMockStore();const [active,setActive]=useState<TrackId>("push");const track=tracks.find(t=>t.id===active)!;const points=evolution[active];
 return <section className="page evolution-page"><div className="page-title"><p className="eyebrow"><TrendingUp/> EVOLUÇÃO PESSOAL</p><h1>Olhe o quanto você avançou.</h1><p>Sem comparação. Só a sua história.</p></div>{s.lastSession.length>0&&<div className="impact"><Sparkles/><div><strong>Sua sessão já entrou na jornada</strong><span>+{s.lastSession.length*5} min · novas recomendações calibradas</span></div></div>}
 <div className="metric-grid"><article><Repeat2/><strong>{s.completed}</strong><span>práticas</span></article><article><Clock3/><strong>{s.minutes.toLocaleString("pt-BR")}</strong><span>minutos</span></article><article><Sparkles/><strong>{s.repetitions.toLocaleString("pt-BR")}</strong><span>repetições</span></article></div>
 <div className="track-tabs" aria-label="Escolher trilha">{tracks.map(t=><button key={t.id} className={active===t.id?"active":""} style={{"--track":t.color} as React.CSSProperties} onClick={()=>setActive(t.id)}>{t.icon}<span>{t.name}</span></button>)}</div>
 <article className="capacity-card card" style={{"--track":track.color} as React.CSSProperties}><div><span className="eyebrow">CAPACIDADE · {track.name.toUpperCase()}</span><h2>{track.reference}</h2><p>A mesma carga que antes era difícil agora ficou fácil.</p></div><div className="chart">{points.map((p,i)=><div className="chart-point" key={p.month}><span>{p.value}/min</span><i style={{height:`${35+i*16}%`}}/><b>{p.month}</b><small>{p.effort}</small></div>)}</div></article>
 <h2 className="section-title">Marcos pessoais</h2><div className="milestones">{["Primeira flexão","Primeira barra","Primeiro EMOM completo","50 flexões em 5 minutos","100 práticas concluídas","Primeiro movimento avançado"].map((m,i)=><article className="card" key={m}><span className={i<5?"earned":""}><Award/></span><div><strong>{m}</strong><small>{i<5?"Faz parte da sua história":"Próximo marco"}</small></div></article>)}</div></section>}
