import { act, cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { WorkoutTimer } from "./EmomTimer";
import { enableSignalAudio, playSignal } from "./signalAudio";

vi.mock("./signalAudio", async (importOriginal) => ({ ...await importOriginal<typeof import("./signalAudio")>(), enableSignalAudio: vi.fn(), playSignal: vi.fn() }));
const signal = vi.mocked(playSignal);
const enable = vi.mocked(enableSignalAudio);
const advance = async (milliseconds: number) => act(async () => vi.advanceTimersByTime(milliseconds));
const start = async () => { fireEvent.click(screen.getByRole("button", { name: "Começar contagem" })); await act(async () => {}); };

describe("WorkoutTimer", () => {
  beforeEach(() => { vi.useFakeTimers(); signal.mockClear(); enable.mockClear(); Object.defineProperty(navigator, "vibrate", { configurable: true, value: vi.fn() }); });
  afterEach(() => { cleanup(); vi.useRealTimers(); });
  it("inicia com dez segundos e sinaliza os cinco segundos antes da largada", async () => { render(<WorkoutTimer exercise="Flexão no solo" reps={12} onFinish={() => {}} />); expect(screen.getByText("Começa em 10")).toBeVisible(); await start(); expect(enable).toHaveBeenCalledOnce(); await advance(4_999); expect(signal).not.toHaveBeenCalled(); await advance(5_001); expect(signal.mock.calls.filter(([kind]) => kind === "prepare")).toHaveLength(5); expect(signal.mock.calls.filter(([kind]) => kind === "start")).toHaveLength(1); });
  it("sinaliza os cinco segundos anteriores ao minuto e a virada", async () => { render(<WorkoutTimer reps={5} onFinish={() => {}} />); await start(); await advance(69_900); expect(signal.mock.calls.filter(([kind]) => kind === "prepare")).toHaveLength(10); expect(signal.mock.calls.filter(([kind]) => kind === "start")).toHaveLength(1); await advance(100); expect(signal.mock.calls.filter(([kind]) => kind === "start")).toHaveLength(2); });
  it("não duplica sinais após pausa, retomada ou retorno da aba", async () => { render(<WorkoutTimer reps={5} onFinish={() => {}} />); await start(); await advance(12_000); fireEvent.click(screen.getByRole("button", { name: "Pausar" })); const before = signal.mock.calls.length; await advance(60_000); document.dispatchEvent(new Event("visibilitychange")); expect(signal).toHaveBeenCalledTimes(before); fireEvent.click(screen.getByRole("button", { name: "Continuar" })); await act(async () => {}); await advance(58_000); const atTurn = signal.mock.calls.length; document.dispatchEvent(new Event("visibilitychange")); expect(signal).toHaveBeenCalledTimes(atTurn); expect(signal.mock.calls.filter(([kind]) => kind === "start")).toHaveLength(2); });
  it("expõe e persiste controles, teste, som desligado e volume", async () => { const update = vi.fn(); const preferences = { sound: false, volume: .2, vibration: false }; render(<WorkoutTimer reps={5} preferences={preferences} updatePreferences={update} onFinish={() => {}} />); expect(screen.getByRole("checkbox", { name: "Sinais sonoros" })).not.toBeChecked(); expect(screen.getByRole("slider", { name: "Volume" })).toHaveValue("0.2"); expect(screen.getByRole("slider", { name: "Volume" })).toBeDisabled(); fireEvent.click(screen.getByRole("checkbox", { name: "Sinais sonoros" })); expect(update).toHaveBeenCalledWith({ sound: true }); fireEvent.change(screen.getByRole("slider", { name: "Volume" }), { target: { value: ".7" } }); expect(update).toHaveBeenCalledWith({ volume: .7 }); fireEvent.click(screen.getByRole("button", { name: "Testar sinal" })); await act(async () => {}); expect(enable).toHaveBeenCalled(); expect(signal).toHaveBeenLastCalledWith("start", expect.objectContaining({ sound: true, volume: .7 })); });
  it("confirma interrupção sem estimar volume", async () => { const stop = vi.fn(); render(<WorkoutTimer reps={7} onFinish={() => {}} onInterrupt={stop} />); await start(); await advance(12_000); fireEvent.click(screen.getByRole("button", { name: "Pausar" })); fireEvent.click(screen.getByRole("button", { name: "Encerrar treino" })); expect(screen.getByText(/nenhum volume será estimado/)).toBeVisible(); fireEvent.click(screen.getByRole("button", { name: "Marcar como interrompido" })); expect(stop).toHaveBeenCalled(); });
});
