import { act, cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { WorkoutTimer } from "./EmomTimer";
import { enableSignalAudio, playSignal } from "./signalAudio";

vi.mock("./signalAudio", async (importOriginal) => ({ ...await importOriginal<typeof import("./signalAudio")>(), enableSignalAudio: vi.fn(), playSignal: vi.fn() }));
const signal = vi.mocked(playSignal);
const enable = vi.mocked(enableSignalAudio);
const advance = async (milliseconds: number) => act(async () => vi.advanceTimersByTime(milliseconds));
const start = async () => { fireEvent.click(screen.getByRole("button", { name: "Iniciar" })); await act(async () => {}); };

describe("WorkoutTimer", () => {
  beforeEach(() => { vi.useFakeTimers(); signal.mockClear(); enable.mockClear(); Object.defineProperty(navigator, "vibrate", { configurable: true, value: vi.fn() }); });
  afterEach(() => { cleanup(); vi.useRealTimers(); });
  it("mostra a preparação sem expor a modalidade", () => { render(<WorkoutTimer exercise="Flexão no solo" reps={12} onFinish={() => {}} />); expect(screen.getByRole("timer", { name: "10 segundos" })).toHaveTextContent("00:10"); expect(screen.getByText("ROUND 1 DE 5")).toBeVisible(); expect(screen.getByLabelText("Round 1")).toHaveTextContent("1"); expect(screen.queryByText("Flexão no solo")).not.toBeInTheDocument(); });
  it("mantém 10 a 6 silenciosos, sinaliza 5 a 2 e comanda no segundo 1", async () => { render(<WorkoutTimer reps={12} onFinish={() => {}} />); await start(); expect(enable).toHaveBeenCalledOnce(); await advance(4_999); expect(signal).not.toHaveBeenCalled(); await advance(1); expect(screen.getByRole("timer", { name: "5 segundos" })).toHaveTextContent("00:05"); expect(screen.getByLabelText("Cronômetro")).toHaveAttribute("data-state", "attention"); await advance(3_000); expect(signal.mock.calls.filter(([kind]) => kind === "prepare")).toHaveLength(4); await advance(1_000); expect(signal.mock.calls.filter(([kind]) => kind === "start")).toHaveLength(1); expect(screen.getByLabelText("Cronômetro")).toHaveAttribute("data-state", "command"); });
  it("sinaliza antes do minuto e vira o placar sem som adicional", async () => { render(<WorkoutTimer reps={5} onFinish={() => {}} />); await start(); await advance(69_900); expect(signal.mock.calls.filter(([kind]) => kind === "prepare")).toHaveLength(8); expect(signal.mock.calls.filter(([kind]) => kind === "start")).toHaveLength(2); await advance(100); expect(screen.getByText("ROUND 2 DE 5")).toBeVisible(); expect(screen.getByLabelText("Round 2")).toHaveTextContent("2"); expect(screen.getByRole("timer", { name: "60 segundos" })).toHaveTextContent("01:00"); expect(signal.mock.calls.filter(([kind]) => kind === "start")).toHaveLength(2); });
  it("não duplica sinais após pausa, retomada ou retorno da aba", async () => { render(<WorkoutTimer reps={5} onFinish={() => {}} />); await start(); await advance(12_000); fireEvent.click(screen.getByRole("button", { name: "Pausar" })); const before = signal.mock.calls.length; await advance(60_000); document.dispatchEvent(new Event("visibilitychange")); expect(signal).toHaveBeenCalledTimes(before); fireEvent.click(screen.getByRole("button", { name: "Continuar" })); await act(async () => {}); await advance(58_000); const atTurn = signal.mock.calls.length; document.dispatchEvent(new Event("visibilitychange")); expect(signal).toHaveBeenCalledTimes(atTurn); expect(signal.mock.calls.filter(([kind]) => kind === "start")).toHaveLength(2); });
  it("expõe e persiste o controle secundário de áudio", () => { const update = vi.fn(); const preferences = { sound: false, volume: .2, vibration: false }; render(<WorkoutTimer reps={5} preferences={preferences} updatePreferences={update} onFinish={() => {}} />); const audio = screen.getByRole("button", { name: "Áudio desligado" }); expect(audio).toHaveAttribute("aria-pressed", "false"); fireEvent.click(audio); expect(update).toHaveBeenCalledWith({ sound: true }); expect(screen.getByRole("button", { name: "Áudio ligado" })).toHaveAttribute("aria-pressed", "true"); });
  it("encerra o último round somente com o sinal exclusivo de conclusão", async () => { const finish = vi.fn(); render(<WorkoutTimer reps={5} onFinish={finish} />); await start(); await advance(310_000); expect(signal.mock.calls.filter(([kind]) => kind === "finish")).toHaveLength(1); expect(signal.mock.calls.at(-1)?.[0]).toBe("finish"); expect(finish).toHaveBeenCalledWith(300); });
  it("mantém round de dois dígitos e extremos do cronômetro íntegros em dez rounds", async () => { const prescription = { track: "push" as const, exerciseKey: "floor-push-up", suggestedShortReps: 5, chosenShortReps: 5, displayedReps: 5, sets: 10, estimatedVolume: 50 }; render(<WorkoutTimer prescriptions={[prescription]} onFinish={() => {}} />); await start(); await advance(560_000); expect(screen.getByText("ROUND 10 DE 10")).toBeVisible(); expect(screen.getByLabelText("Round 10")).toHaveTextContent("10"); expect(screen.getByRole("timer", { name: "50 segundos" })).toHaveTextContent("00:50"); await advance(49_000); expect(screen.getByRole("timer", { name: "1 segundo" })).toHaveTextContent("00:01"); });
  it("confirma interrupção sem estimar volume", async () => { const stop = vi.fn(); render(<WorkoutTimer reps={7} onFinish={() => {}} onInterrupt={stop} />); await start(); await advance(12_000); fireEvent.click(screen.getByRole("button", { name: "Pausar" })); fireEvent.click(screen.getByRole("button", { name: "Encerrar" })); expect(screen.getByText(/nenhum volume será estimado/)).toBeVisible(); fireEvent.click(screen.getByRole("button", { name: "Marcar como interrompido" })); expect(stop).toHaveBeenCalled(); });
});
