import type{Arrival,DurationChoice,Perception,SessionPrescription,TrackId,WorkoutSession}from"@/mocks/data";
export const SETS={short:5,long:10}as const;
export const arrivalAdjustment:Record<Arrival,number>={empty:-2,slow:-1,normal:0,ready:1,whole:1};
export const longReps=(n:number)=>Math.max(1,Math.ceil(n/2));
export const displayedReps=(n:number,d:DurationChoice)=>d==="short"?n:longReps(n);
export const estimatedVolume=(n:number,d:DurationChoice)=>displayedReps(n,d)*SETS[d];
export const conventionalLimit=(n:number)=>Math.round(n*1.2);export const conventionalFloor=(n:number)=>Math.round(n*.8);
export const isLargeIncrease=(suggestion:number,chosen:number)=>chosen>conventionalLimit(suggestion);export const isLargeReduction=(suggestion:number,chosen:number)=>chosen<conventionalFloor(suggestion);
export const positive=(p?:Perception)=>p==="right"||p==="light"||p==="spare";
export function prescriptionOf(s:WorkoutSession,t:TrackId){return s.prescriptions.find(p=>p.track===t)}
export function completedForTrack(h:WorkoutSession[],t:TrackId){return h.filter(s=>s.status==="completed"&&!!prescriptionOf(s,t))}
export type Recommendation={reference:number;value:number;message:string;cautiousReference?:number};
export function recommend(track:TrackId,initial:number,history:WorkoutSession[]):Recommendation{const complete=completedForTrack(history,track),last=complete.at(-1);if(!last)return{reference:initial,value:initial,message:"Vamos encontrar seu ritmo."};const dose=prescriptionOf(last,track)!,reference=dose.chosenShortReps,previous=complete.at(-2),same=!!previous&&prescriptionOf(previous,track)?.chosenShortReps===reference&&previous.perception===last.perception;if(isLargeIncrease(dose.suggestedShortReps,reference)&&!positive(last.perception))return{reference,value:reference,message:"Com base no que você contou, vamos consolidar essa nova referência.",cautiousReference:reference};switch(last.perception){case"limit":return same?{reference,value:Math.max(1,reference-1),message:"As últimas sessões cobraram bastante. Nossa sugestão é aliviar uma repetição."}:{reference,value:reference,message:"Na última, você chegou no limite. Vamos manter uma referência conhecida."};case"heavy":return{reference,value:reference,message:"Foi pesado, mas você sustentou o ritmo. Vamos manter."};case"right":return same?{reference,value:reference+1,message:"Duas sessões na medida. Que tal uma repetição a mais?"}:{reference,value:reference,message:"Esse ritmo funcionou bem. Vamos consolidar mais uma vez."};case"light":return{reference,value:reference+1,message:"Você terminou com margem. Nossa sugestão avançou uma repetição."};case"spare":return{reference,value:reference+1,message:"Sobrou energia na última. Parece um bom momento para avançar."};default:return{reference,value:reference,message:"Você já sustentou esse ritmo."}}}
export function contextualMessage(s:number,c:number,known:number[]){if(known.includes(c)&&c!==s)return"Voltando para uma referência conhecida.";if(isLargeIncrease(s,c))return"Opa, isso é um salto grande. Parece realista para todas as séries?";if(c>s)return"Boa. Um avanço dentro do seu ritmo.";if(isLargeReduction(s,c))return"Indo com mais calma hoje? Você conhece seu momento. Vamos nesse ritmo.";return"Você já sustentou esse ritmo."}
export function makePrescription(track:TrackId,exerciseKey:SessionPrescription["exerciseKey"],suggested:number,chosen:number,duration:DurationChoice):SessionPrescription{return{track,exerciseKey,suggestedShortReps:suggested,chosenShortReps:chosen,displayedReps:displayedReps(chosen,duration),sets:SETS[duration],estimatedVolume:estimatedVolume(chosen,duration)}}
export function sequence<T extends{track:TrackId}>(items:T[],sets:number,format:"blocks"|"circuit"){return format==="blocks"?items.flatMap(i=>Array.from({length:sets},()=>i)):Array.from({length:sets},()=>items).flat()}
