"use client";
import{useMemo,useState}from"react";import{tracks,localDateString,type Arrival,type DurationChoice,type Perception,type TrackId,type WorkoutFormat,type WorkoutSession}from"@/mocks/data";import{useMockStore}from"@/mocks/store";import{arrivalAdjustment,contextualMessage,displayedReps,estimatedVolume,isLargeIncrease,makePrescription,recommend,SETS}from"./recommendationEngine";import{TrackSelector}from"./TrackSelector";import{WorkoutSequence}from"./WorkoutSequence";import{WorkoutTimer}from"./EmomTimer";import{WorkoutPulse}from"./WorkoutPulse";
const arrivals:[Arrival,string,string][]=[["empty","Sem energia","−2"],["slow","Devagar","−1"],["normal","Normal","0"],["ready","Disposto","+1"],["whole","Inteiro","+1"]];
type Step="tracks"|"arrival"|"duration"|"format"|"review"|"running"|"pulse"|"done";
export function WorkoutFlow({onClose,initialTrack}:{onClose:()=>void;initialTrack?:TrackId}){const store=useMockStore(),[step,setStep]=useState<Step>("tracks"),[selected,setSelected]=useState<TrackId[]>(initialTrack?[initialTrack]:[]),[arrival,setArrival]=useState<Arrival|null>(null),[duration,setDuration]=useState<DurationChoice|null>(null),[format,setFormat]=useState<WorkoutFormat>("blocks"),[chosen,setChosen]=useState<Partial<Record<TrackId,number>>>({}),[pending,setPending]=useState<WorkoutSession|null>(null),[milestones,setMilestones]=useState<string[]>([]);const today=localDateString(),repeated=tracks.filter(t=>store.sessions.some(s=>s.date===today&&s.prescriptions.some(p=>p.track===t.id))).map(t=>t.id);
const recommendations=useMemo(()=>Object.fromEntries(tracks.map(t=>[t.id,recommend(t.id,t.initialShortRecommendation,store.sessions)]))as Record<TrackId,ReturnType<typeof recommend>>,[store.sessions]);
function toggle(id:TrackId){setSelected(s=>s.includes(id)?s.filter(x=>x!==id):s.length<4?[...s,id]:s)}function selectArrival(a:Arrival){setArrival(a);const delta=arrivalAdjustment[a];setChosen(Object.fromEntries(selected.map(id=>[id,Math.max(1,recommendations[id].value+delta)])));setStep("duration")}
const prescriptions=duration?selected.map(id=>{const t=tracks.find(x=>x.id===id)!;const suggestion=Math.max(1,recommendations[id].value+arrivalAdjustment[arrival||"normal"]);return makePrescription(id,t.exerciseKey,suggestion,chosen[id]??suggestion,duration)}):[];
function begin(){const now=new Date(),id=`session-${now.getTime()}`;setPending({id,combinedId:id,date:today,time:now.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"}),duration:duration!,format,arrival:arrival!,plannedMinutes:selected.length*(duration==="long"?10:5),elapsedSeconds:0,status:"completed",prescriptions});setStep("running")}
function interrupt(seconds:number){if(!pending)return;store.completeSession({...pending,status:"interrupted",elapsedSeconds:seconds,prescriptions:pending.prescriptions.map(p=>({...p,estimatedVolume:undefined}))});onClose()}
function complete(p:Perception){if(!pending)return;const finished={...pending,perception:p,elapsedSeconds:pending.plannedMinutes*60}as WorkoutSession;const wins:string[]=[];for(const dose of finished.prescriptions){const t=tracks.find(x=>x.id===dose.track)!,past=store.sessions.filter(s=>s.status==="completed").flatMap(s=>s.prescriptions.filter(x=>x.track===dose.track));if(!past.length||dose.chosenShortReps>Math.max(...past.map(x=>x.chosenShortReps)))wins.push(`Novo ponto mais alto: ${dose.chosenShortReps} por série.`);if(!past.length||(dose.estimatedVolume||0)>Math.max(...past.map(x=>x.estimatedVolume||0)))wins.push(`Seu maior volume estimado em ${t.name}: ${dose.estimatedVolume} movimentos.`)}store.completeSession(finished);setMilestones(wins);setStep("done")}
return <div className="workout-builder" role="dialog" aria-modal="true" aria-label="Montar treino"><header><div><small>NOVO TREINO</small><h1>Monte seu ritmo</h1></div><button onClick={onClose} aria-label="Fechar">×</button></header><main>
{step==="tracks"&&<section className="builder-step"><p className="step-label">1 · TRILHAS</p><h2>O que entra neste treino?</h2><TrackSelector selected={selected} onToggle={toggle} repeated={repeated}/>{selected.some(x=>repeated.includes(x))&&<aside className="recovery-note">Você já treinou esta trilha hoje. Mais uma sessão pode cobrar bastante do mesmo movimento. Quer continuar? A escolha é sua.</aside>}<button className="primary-button" disabled={!selected.length} onClick={()=>setStep("arrival")}>Continuar</button></section>}
{step==="arrival"&&<section className="builder-step"><p className="step-label">2 · CONDIÇÃO</p><h2>Como você chega para este treino?</h2><div className="arrival-control" role="radiogroup">{arrivals.map(([id,label,delta])=><button role="radio" aria-checked={arrival===id} key={id} onClick={()=>selectArrival(id)}><i/><strong>{label}</strong><small>{delta}</small></button>)}</div></section>}
{step==="duration"&&<section className="builder-step"><p className="step-label">3 · DURAÇÃO</p><h2>Escolha um ritmo para todas as trilhas</h2><div className="duration-options">{(["short","long"]as DurationChoice[]).map(d=><button key={d} onClick={()=>{setDuration(d);setStep(selected.length>1?"format":"review")}}><strong>{d==="short"?"Curto":"Longo"}</strong><span>{selected.length*SETS[d]} minutos</span>{selected.map(id=>{const n=Math.max(1,recommendations[id].value+arrivalAdjustment[arrival!]);return <small key={id}>{tracks.find(t=>t.id===id)!.name}: {displayedReps(n,d)} por série · volume estimado {estimatedVolume(n,d)}</small>})}</button>)}</div></section>}
{step==="format"&&<section className="builder-step"><p className="step-label">4 · FORMATO</p><h2>Como as trilhas se alternam?</h2><div className="format-options"><button onClick={()=>{setFormat("blocks");setStep("review")}}><strong>Blocos</strong><span>Todos os minutos de uma trilha antes da próxima.</span></button><button onClick={()=>{setFormat("circuit");setStep("review")}}><strong>Circuito</strong><span>As trilhas alternam minuto a minuto.</span></button></div></section>}
{step==="review"&&<section className="builder-step review-step"><p className="step-label">5 · REVISÃO</p><h2>{selected.length*SETS[duration!]} minutos · {format==="blocks"?"Blocos":"Circuito"}</h2><div className="prescription-list">{prescriptions.map(p=>{const t=tracks.find(x=>x.id===p.track)!,known=store.sessions.flatMap(s=>s.prescriptions.filter(x=>x.track===p.track).map(x=>x.chosenShortReps)),message=contextualMessage(p.suggestedShortReps,p.chosenShortReps,known);return <article key={p.track} style={{"--track":t.color}as React.CSSProperties}><div><small>{t.name}</small><h3>{t.exercise}</h3><p>{p.displayedReps} por série · {p.sets} minutos · volume estimado {p.estimatedVolume}</p></div><div className="dose-control"><button aria-label={`Diminuir repetições de ${t.name}`} onClick={()=>setChosen(v=>({...v,[p.track]:Math.max(1,(v[p.track]??p.suggestedShortReps)-1)}))}>−</button><strong>{p.displayedReps}</strong><button aria-label={`Aumentar repetições de ${t.name}`} onClick={()=>setChosen(v=>({...v,[p.track]:(v[p.track]??p.suggestedShortReps)+1}))}>+</button></div><p className="context-message">{message}</p>{isLargeIncrease(p.suggestedShortReps,p.chosenShortReps)&&<div className="choice-actions"><button>Manter minha escolha</button><button onClick={()=>setChosen(v=>({...v,[p.track]:p.suggestedShortReps}))}>Voltar à sugestão</button></div>}</article>})}</div><WorkoutSequence prescriptions={prescriptions} mode={format}/><button className="primary-button" onClick={begin}>Iniciar treino</button></section>}
{step==="running"&&pending&&<WorkoutTimer prescriptions={pending.prescriptions} format={pending.format} preferences={store.preferences} onFinish={()=>setStep("pulse")} onInterrupt={interrupt}/>} {step==="pulse"&&<WorkoutPulse onConfirm={complete}/>} {step==="done"&&<section className="builder-step completion-step"><p className="step-label">REGISTRO INCORPORADO</p><h2>Treino concluído.</h2>{milestones.length?<ul>{milestones.map(m=><li key={m}>{m}</li>)}</ul>:<p>Mais uma referência para a sua jornada.</p>}<button className="primary-button" onClick={onClose}>Voltar à jornada</button></section>}
</main></div>}
