"use client";
import { Check, ChevronLeft, ChevronRight, Flame, HeartPulse, Lightbulb, Pause, Play, RotateCcw, Sparkles, X } from "lucide-react";
import { useState } from "react";import { type Effort } from "@/mocks/data";import { type CompletedPractice, useMockStore } from "@/mocks/store";
type Phase="warmup"|"suggestion"|"timer"|"feedback"|"adapted"|"done";
const efforts:[Effort,string][]=[["Muito fáceis","😄"],["Fáceis","🙂"],["Moderadas","😌"],["Difíceis","😤"],["Muito difíceis","🥵"],["Não completei","↩"]];
export function WorkoutFlow({onClose}:{onClose:()=>void}){const store=useMockStore();const queue=store.session;const [phase,setPhase]=useState<Phase>("warmup");const [index,setIndex]=useState(0);const [minute,setMinute]=useState(1);const [running,setRunning]=useState(false);const [accepted,setAccepted]=useState(false);const [results,setResults]=useState<CompletedPractice[]>([]);const [gain,setGain]=useState(0);const current=queue[index];
 function choose(e:Effort){const result=store.adapt(current,e);setResults(v=>[...v,result]);setPhase("adapted")}
 function next(){if(index<queue.length-1){setIndex(v=>v+1);setMinute(1);setRunning(false);setAccepted(false);setPhase("suggestion")}else{const xp=store.finishSession(results);setGain(xp);setPhase("done")}}
 return <div className="modal workout-modal" role="dialog"><header className="flow-header"><button onClick={onClose}><ChevronLeft/></button><div><span>{phase==="warmup"?"PREPARAÇÃO":phase==="done"?"SESSÃO CONCLUÍDA":`PRÁTICA ${index+1} DE ${queue.length}`}</span><strong>{phase==="warmup"?"Aquecimento":phase==="done"?"Sua jornada continua":current?.name}</strong></div><button onClick={onClose}><X/></button></header>
 <main className="flow-content">{phase==="warmup"&&<section className="flow-center"><span className="big-icon warm"><HeartPulse/></span><p className="eyebrow">ANTES DAS PRÁTICAS</p><h1>Aquecimento</h1><p>Prepare articulações e encontre seu ritmo.</p><div className="warmup-list"><span><Check/> Mobilidade de ombros <b>40s</b></span><span><Check/> Agachamentos leves <b>40s</b></span><span><Check/> Polichinelos <b>40s</b></span></div><button className="primary-button" onClick={()=>setPhase("suggestion")}>ESTOU PRONTO <ChevronRight/></button></section>}
 {phase==="suggestion"&&<section className="flow-center"><span className="big-icon idea"><Lightbulb/></span><p className="eyebrow">EXPERIMENTE · OPCIONAL</p><h1>Quer tornar esta prática mais interessante?</h1><div className="suggestion-card"><strong>{current.name}</strong><p>{current.suggestion}</p></div><button className="primary-button" onClick={()=>{setAccepted(true);setPhase("timer")}}><Sparkles/> ACEITAR SUGESTÃO</button><button className="text-button" onClick={()=>setPhase("timer")}>CONTINUAR NORMALMENTE</button></section>}
 {phase==="timer"&&<section className="flow-center timer-screen"><p className="eyebrow">EMOM · 5 MINUTOS</p><h1>{current.name}</h1><p>{current.dose} {current.unit==="reps"?"repetições":"segundos"} a cada minuto</p>{accepted&&<span className="accepted"><Sparkles/> Sugestão aceita</span>}<div className="minute-ring"><small>SÉRIE</small><strong>{minute}</strong><span>de 5</span></div><div className="series-dots">{[1,2,3,4,5].map(n=><i className={n<minute?"done":n===minute?"active":""} key={n}>{n<minute?<Check/>:n}</i>)}</div><button className="primary-button timer-button" onClick={()=>{if(minute===5)setPhase("feedback");else setMinute(v=>v+1);setRunning(true)}}>{running?<><ChevronRight/> CONCLUIR SÉRIE {minute}</>:<><Play/> INICIAR EMOM</>}</button><button className="text-button" onClick={()=>setRunning(v=>!v)}>{running?<><Pause/> PAUSAR</>:<><RotateCcw/> RECOMEÇAR</>}</button></section>}
 {phase==="feedback"&&<section className="flow-center feedback"><p className="eyebrow">UMA RESPOSTA. SÓ ISSO.</p><h1>Como foram as séries 4 e 5?</h1><p>Isso ajuda a calibrar sua próxima prática.</p><div className="effort-grid">{efforts.map(([label,emoji])=><button key={label} onClick={()=>choose(label)}><i>{emoji}</i><span>{label}</span></button>)}</div></section>}
 {phase==="adapted"&&(()=>{const r=results.at(-1)!;return <section className="flow-center"><span className="big-icon success"><Check/></span><p className="eyebrow">MOTOR ADAPTATIVO</p><h1>Próximo estímulo calibrado.</h1><p>Seu feedback virou uma recomendação — não uma nota.</p><div className="adapt-card"><span>HOJE<strong>{r.previousDose} /min</strong></span><ChevronRight/><span>PRÓXIMA VEZ<strong>{r.nextDose} /min</strong></span></div><small className="prototype-note">Regra provisória do protótipo. Poderá ser substituída pelo motor definitivo.</small><button className="primary-button" onClick={next}>{index<queue.length-1?"PRÓXIMA PRÁTICA":"FINALIZAR SESSÃO"}<ChevronRight/></button></section>})()}
 {phase==="done"&&<section className="flow-center"><span className="big-icon finish"><Flame/></span><p className="eyebrow">SESSÃO CONCLUÍDA</p><h1>Você avançou hoje.</h1><p>{queue.length} práticas · {queue.length*5} minutos · uma jornada só sua.</p><div className="xp-earned"><Sparkles/><span><small>EXPERIÊNCIA GANHA</small><strong>+{gain} XP</strong></span></div><p className="completion-note">Capacidade física e XP continuam separados. Suas recomendações já foram recalibradas.</p><button className="primary-button" onClick={onClose}>VOLTAR À JORNADA</button></section>}</main></div>}
