import { act,cleanup,fireEvent,render,screen,within } from "@testing-library/react";
import { afterEach,describe,it,expect,vi } from "vitest";
import { MockStoreProvider } from "@/mocks/store";
import { Trail } from "@/features/trail/Trail";

afterEach(()=>{cleanup();vi.useRealTimers()});
function openTwo(){render(<MockStoreProvider><Trail/></MockStoreProvider>);fireEvent.click(screen.getByRole("button",{name:/Selecionar sugestão de Empurrar/}));fireEvent.click(screen.getByRole("button",{name:/Selecionar sugestão de Puxar/}));fireEvent.click(screen.getByRole("button",{name:"INICIAR"}))}
function completeSet(last=false){for(let i=0;i<3;i++)act(()=>vi.advanceTimersByTime(1000));fireEvent.click(screen.getByRole("button",{name:"TERMINEI"}));if(!last)fireEvent.click(screen.getByRole("button",{name:"PRÓXIMA SÉRIE"}))}

describe("WorkoutFlow",()=>{
  it("calcula cinco séries, destaques, volumes e duração",()=>{openTwo();expect(screen.getAllByText(/5 séries/)).toHaveLength(2);const cards=document.querySelectorAll(".practice-card");expect(within(cards[0] as HTMLElement).getByText("14")).toHaveClass("reps-number");expect(within(cards[1] as HTMLElement).getByText("7")).toHaveClass("reps-number");expect(within(cards[0] as HTMLElement).getByText("70")).toBeInTheDocument();expect(within(cards[1] as HTMLElement).getByText("35")).toBeInTheDocument();expect(screen.getByText("105")).toBeInTheDocument();expect(screen.getAllByText("10 min").length).toBeGreaterThanOrEqual(1)});
  it("inverte e preserva a ordem escolhida",()=>{openTwo();fireEvent.click(screen.getByRole("button",{name:"Inverter ordem das práticas"}));const cards=document.querySelectorAll(".practice-card");expect(within(cards[0] as HTMLElement).getByRole("heading",{name:"Barra fixa"})).toBeInTheDocument();expect(within(cards[1] as HTMLElement).getByRole("heading",{name:"Flexão de braço no solo"})).toBeInTheDocument()});
  it("faz o aquecimento e executa cinco séries completas antes da segunda prática",()=>{vi.useFakeTimers();openTwo();fireEvent.click(screen.getByRole("button",{name:"AQUECER"}));expect(screen.getByText("Flexão inclinada")).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"COMEÇAR AQUECIMENTO"}));expect(screen.getByRole("heading",{name:"Flexão inclinada"})).toBeInTheDocument();for(let i=0;i<4;i++)fireEvent.click(screen.getByRole("button",{name:i===3?"CONCLUIR":"CONTINUAR"}));expect(screen.getByRole("heading",{name:"Treino pronto"})).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:/INICIAR FLEXÃO/}));for(let i=1;i<=5;i++){expect(screen.getByText(`SÉRIE ${i}/5`)).toBeInTheDocument();completeSet(i===5)}expect(screen.getByText("PUXAR · 2 DE 2")).toBeInTheDocument();expect(screen.getByRole("heading",{name:"Barra fixa"})).toBeInTheDocument();expect(screen.getByText("SÉRIE 1/5")).toBeInTheDocument()});
});
